---

- name: ensure a folder exists for integration tests
  file:
    state: directory
    path: "{{ runfolder_path }}"
    owner: "{{ arteria_user }}"

- name: create runfolder-ws-test, script for executing integration tests
  template:
    src: runfolder-ws-test.j2
    dest: "/usr/local/bin/runfolder-ws-test"
    mode: "u+x"
    owner: "{{ arteria_user }}"

- name: running integration tests for runfolder...
  shell: sleep 2 && /usr/local/bin/runfolder-ws-test
  ignore_errors: true

