---

- include: sources.yml
  tags: runfolder_sources

- include: install.yml
  tags: runfolder_install

- include: install_config.yml
  tags: runfolder_install

- supervisorctl:
    name: runfolder-ws
    state: restarted
    supervisorctl_path: /usr/local/bin/supervisorctl

- include: integration_test.yml
  tags: runfolder_integration_test
  when: arteria_environment == "staging"

