---

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Install python-compile pre-reqs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib-devel
    - openssl-devel
    - sqlite-devel
    - bzip2-devel
    - wget
    - tar

- name: Get python sources
  get_url:
    url: https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
    dest: /usr/src/Python-2.7.10.tgz
    sha256sum: eda8ce6eec03e74991abb5384170e7c65fcd7522e409b8e83d7e6372add0f12a

- name: Untar python sources
  unarchive: src=/usr/src/Python-2.7.10.tgz dest=/usr/src copy=no

- name: compile python
  shell: ./configure && make --quiet altinstall && touch ansible_state_completed
  args:
    chdir: /usr/src/Python-2.7.10
    creates: /usr/src/Python-2.7.10/ansible_state_completed

- name: download python setup-tools
  get_url:
    url: https://pypi.python.org/packages/source/s/setuptools/setuptools-1.4.2.tar.gz
    dest: /usr/src/
    sha256sum: 263986a60a83aba790a5bffc7d009ac88114ba4e908e5c90e453b3bf2155dbbd

- name: Untar setup-tools
  unarchive:
    src: /usr/src/setuptools-1.4.2.tar.gz
    dest: /usr/src
    copy: no

- name: install setup-tools
  shell: /usr/local/bin/python2.7 setup.py install && touch /usr/src/setuptools-1.4.2/ansible_state_completed
  args:
    chdir: /usr/src/setuptools-1.4.2
    creates: /usr/src/setuptools-1.4.2/ansible_state_completed

- name: install pip
  shell: curl -q https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py | /usr/local/bin/python2.7 -

- name: install other packages
  pip:
    name: "{{ item }}"
    executable: /usr/local/bin/pip
  with_items:
    - virtualenv
    - supervisor

- name: create supervisor directories
  file:
    path: /etc/supervisor/conf.d
    state: directory

- name: create supervisor directories
  file:
    path: /var/log/supervisor/
    state: directory

- name: deploy supervisord config
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf

- name: deploy supervisord_init
  template:
    src: supervisord_init.j2
    dest: /etc/init.d/supervisord
    mode: u+x

- name: chkconfig --add supervisord
  shell: chkconfig --add supervisord

- name: start supervisord
  service:
    name: supervisord
    state: started

- name: ensure /var/log/arteria dir exists
  file:
    state: directory
    path: /var/log/arteria
    owner: "{{ arteria_user }}"

- name: ensure /etc/arteria dir exists
  file:
    state: directory
    path: /etc/arteria

- name: disable iptables
  service: name=iptables state=stopped enabled=no
  when: arteria_disable_iptables
