---


arteria_sisyphus_user: vagrant
install_path: /opt/arteria/

arteria_siswrap_path: "{{ install_path }}/arteria-siswrap-env"
sisyphus_path: "{{ arteria_siswrap_path }}/deps/sisyphus/"
sisyphus_git_repo: https://github.com/Molmed/sisyphus.git
sisyphus_repo_branch: master
